#!/usr/bin/sh

source "$(dirname $0)"/common.sh

state() {
    S=$(acpi --battery)
    S=${S//,/ }
    A=($S)
    if [ "${A[2]}" = 'Unknown' ]; then
        printf '%s' "${A[3]}"
    elif [ "${A[2]}" = 'Full' ]; then
        printf '%s, connected to charger, full' "${A[3]}"
    elif [ "${A[2]}" = 'Discharging' ]; then
        printf '%s, discharging, %s until empty' "${A[3]}" "${A[4]}"
    else
        if [ "${A[4]}" = 'charging' ]; then
            A[4]='??:??:??'
        fi
        printf '%s, charging, %s until full' "${A[3]}" "${A[4]}" 
    fi
}

hide_cursor
disable_echo
while true; do
    text=$(state) 
    reshape $(echo "$text" | shape_of)
    printf '%s' "$text"
    sleep 1
    move_top_left
done
