#!/usr/bin/sh

source "$(dirname $0)"/common.sh

width=100

view() (
    S=$(acpi --battery)
    S=${S//,/ }
    S=${S//%/ }
    A=($S)
    status="${A[2]}"
    amount="${A[3]}"
    period="${A[4]}"
    if [ "$status" = 'Unknown' ]; then
        left=
        right=
        ts='| '
    elif [ "$status" = 'Full' ]; then
        left=
        right=00:00:00
        ts='| '
    elif [ "$status" = 'Discharging' ]; then
        left=$period
        right=''
        ts='[ '
    elif [ "$status" = 'Charging' ]; then
        left=
        if [ $period = 'charging' ]; then
            right=??:??:??
        else
            right=$period
        fi
        ts='] '
    fi
    trialign $width "$left" $amount% "$right"
    printf '\n'
    bar $width "$ts" $amount
)

hide_cursor
disable_echo
while true; do
    render "$(view)" 
    sleep 1
done
