#!/usr/bin/sh

source "$(dirname $0)"/common.sh

entries=(
    't' 'Terminal'          'xterm'
    'b' 'Browser'           'chromium'
    'B' 'Incognito Browser' 'chromium --incognito'
    'f' 'File Manager'      'Thunar'
)

menu() (
    i=0
    while [ $i -lt ${#entries[@]} ]; do
        key=${entries[i]}
        i=$(expr $i + 1)
        name=${entries[i]}
        i=$(expr $i + 1)
        cmd=${entries[i]}
        i=$(expr $i + 1)
        printf '%s - %s\n' "$key" "$name"
    done
)

hide_cursor
disable_echo
reshape_and_print "$(menu)" 
while read -rsn1 k; do
    read -t 0.0001 -rsn1 kk && k+=$kk
    read -t 0.0001 -rsn1 kk && k+=$kk
    read -t 0.0001 -rsn1 kk && k+=$kk
    read -t 0.0001 -rsn1 kk && k+=$kk
    read -t 0.0001 -rsn1 kk && k+=$kk

    i=0
    while [ $i -lt ${#entries[@]} ]; do
        key=${entries[i]}
        i=$(expr $i + 1)
        name=${entries[i]}
        i=$(expr $i + 1)
        cmd=${entries[i]}
        i=$(expr $i + 1)
        if [ "$key" = "$k" ]; then
            setsid $cmd >/dev/null 2>&1 </dev/null &
            sleep 60
            exit
        fi
    done
done
