#!/usr/bin/sh

source "$(dirname $0)"/common.sh

width=100

view() (
    brightness=$(printf '%.0f' "$(xbacklight -get)")
    trialign $width '' $brightness% ''
    printf '\n'
    bar $width '| ' $(printf '%.0f' "$(xbacklight -get)")
)

hide_cursor
disable_echo
while true; do
    render "$(view)" 
    case "$(read_key 0.1)" in
        $'\e[1;3D') # Alt+Left
            xbacklight -time 0 -1
        ;;
        $'\e[D') # Left
            xbacklight -time 0 -10
        ;;
        $'\e[C') # Right
            xbacklight -time 0 +10
        ;;
        $'\e[1;3C') # Alt+Right
            xbacklight -time 0 +1
        ;;
    esac
done
