#!/usr/bin/sh

source "$(dirname $0)"/common.sh

state() {
    date $'+     %B\n%Y-%m-%d %H:%M:%S\n        %A'
}

hide_cursor
disable_echo
while true; do
    text=$(state)
    reshape $(echo "$text" | shape_of)
    printf '%s' "$text"
    sleep 0.02
    move_top_left
done
