#!/usr/bin/sh

tput civis
stty -echo
printf $'\e[8;3;19t'
while true; do
    #       YYYY-MM-DD hh:mm:ss
    printf '     %s\n' $(date "+%B")
    printf '%s %s\n' $(date "+%Y-%m-%d") $(date "+%H:%M:%S")
    printf '        %s' $(date "+%A")
    sleep 0.1
    tput cup 0
done
